"""Generate kernel variations using Claude."""

import re
from dataclasses import dataclass
from pathlib import Path

import anthropic

from krnl.config import KrnlConfig
from krnl.engine.principles import Principle
from krnl.engine.tracker import OptimizationTracker
from krnl.parsers.cutedsl_parser import KernelInfo
from krnl.runner.ncu_profiler import NCUMetrics
from krnl.templates.prompts import (
    SYSTEM_PROMPT,
    VARIATION_USER_PROMPT,
    VARIATION_PARSE_REGEX_KERNEL,
    VARIATION_PARSE_REGEX_LAUNCHER,
)


@dataclass
class GeneratedVariation:
    """A kernel variation generated by the LLM."""

    kernel_code: str
    launcher_code: str | None  # None means no change to launcher
    principles_cited: list[str]
    predicted_effect: str
    raw_response: str


def generate_variations(
    config: KrnlConfig,
    kernel_info: KernelInfo,
    current_best_source: str,
    ncu_metrics: list[NCUMetrics],
    relevant_principles: list[Principle],
    tracker: OptimizationTracker,
    n: int = 1,
) -> list[GeneratedVariation]:
    """Generate n kernel variations using Claude.

    Args:
        config: Runtime config.
        kernel_info: Parsed kernel info (for structure).
        current_best_source: Full source of the current best kernel file.
        ncu_metrics: NCU metrics for the current best kernel.
        relevant_principles: Principles relevant to the current bottleneck.
        tracker: Optimization history tracker.
        n: Number of variations to generate.

    Returns:
        List of generated variations.
    """
    client = anthropic.Anthropic()

    # Build the prompt
    ncu_summary = "\n\n".join(m.summary() for m in ncu_metrics) if ncu_metrics else "No NCU data."
    bottleneck_summary = (
        "\n\n".join(m.bottleneck_summary() for m in ncu_metrics)
        if ncu_metrics
        else "No bottleneck data."
    )
    principles_text = "\n\n".join(p.to_prompt_str() for p in relevant_principles)
    if not principles_text:
        principles_text = "No principles provided."

    best = tracker.get_best()
    parent_id = best.variation_id if best else 0

    user_prompt = VARIATION_USER_PROMPT.format(
        parent_id=parent_id,
        kernel_source=kernel_info.kernel_source,
        launcher_source=kernel_info.launcher_source or "# No separate launcher",
        full_source=current_best_source,
        ncu_summary=ncu_summary,
        bottleneck_summary=bottleneck_summary,
        principles_text=principles_text,
        history=tracker.history_for_llm(),
    )

    variations = []
    for i in range(n):
        # Add variation index hint if generating multiple
        prompt = user_prompt
        if n > 1:
            prompt += (
                f"\n\nThis is variation {i + 1} of {n}. "
                "Try a DIFFERENT optimization strategy than the other variations."
            )

        response = client.messages.create(
            model=config.model,
            max_tokens=8192,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        raw_text = response.content[0].text
        variation = _parse_variation_response(raw_text)
        if variation:
            variations.append(variation)

    return variations


def _parse_variation_response(response_text: str) -> GeneratedVariation | None:
    """Parse the LLM response to extract kernel code and metadata."""
    # Extract kernel code
    kernel_match = re.search(
        VARIATION_PARSE_REGEX_KERNEL, response_text, re.DOTALL
    )
    if not kernel_match:
        return None

    kernel_code = kernel_match.group(1).strip()

    # Extract launcher code
    launcher_code = None
    launcher_match = re.search(
        VARIATION_PARSE_REGEX_LAUNCHER, response_text, re.DOTALL
    )
    if launcher_match:
        launcher_text = launcher_match.group(1).strip()
        if launcher_text.upper() != "NO CHANGE":
            launcher_code = launcher_text

    # Extract principles cited
    principles_section = re.search(
        r"\*\*Principles Applied\*\*:?\s*(.*?)(?=\*\*Predicted Effect\*\*|\*\*Changes Made\*\*)",
        response_text,
        re.DOTALL,
    )
    principles_cited = []
    if principles_section:
        text = principles_section.group(1).strip()
        # Extract principle names from bullet points or inline
        for line in text.split("\n"):
            line = line.strip().lstrip("- •*")
            if line:
                principles_cited.append(line[:100])  # truncate long citations

    # Extract predicted effect
    predicted_effect = ""
    predicted_section = re.search(
        r"\*\*Predicted Effect\*\*:?\s*(.*?)(?=\*\*Changes Made\*\*|\*\*Complete)",
        response_text,
        re.DOTALL,
    )
    if predicted_section:
        predicted_effect = predicted_section.group(1).strip()[:300]

    return GeneratedVariation(
        kernel_code=kernel_code,
        launcher_code=launcher_code,
        principles_cited=principles_cited,
        predicted_effect=predicted_effect,
        raw_response=response_text,
    )
