"""Generate kernel variations using Claude."""

import re
from dataclasses import dataclass
from pathlib import Path

import anthropic

from krnl.config import KrnlConfig
from krnl.engine.principles import Principle
from krnl.engine.tracker import OptimizationTracker
from krnl.parsers.cutedsl_parser import KernelInfo
from krnl.runner.ncu_profiler import NCUMetrics
from krnl.templates.prompts import (
    SYSTEM_PROMPT,
    VARIATION_USER_PROMPT,
    VARIATION_PARSE_REGEX_KERNEL,
    VARIATION_PARSE_REGEX_LAUNCHER,
)

_CUTE_API_REF = (Path(__file__).parent.parent / "templates" / "cute_api_ref.md").read_text()

def _build_system_prompt() -> list[dict]:
    """Build system prompt blocks with prompt caching on the stable cheat-sheet."""
    return [
        {
            "type": "text",
            "text": SYSTEM_PROMPT + "\n\n---\n\n" + _CUTE_API_REF,
            "cache_control": {"type": "ephemeral"},
        }
    ]


@dataclass
class ParentCandidate:
    """A frontier member chosen as the parent for one variation."""

    variation_id: int
    full_source: str       # complete file source for this parent
    kernel_source: str     # @cute.kernel function(s) only
    launcher_source: str   # @cute.jit host launcher source
    ncu_metrics: list[NCUMetrics]
    bottleneck: str        # human-readable bottleneck summary


@dataclass
class GeneratedVariation:
    """A kernel variation generated by the LLM."""

    kernel_code: str
    launcher_code: str | None  # None means no change to launcher
    principles_cited: list[str]
    predicted_effect: str
    raw_response: str
    parent_id: int  # which frontier candidate this was derived from


def generate_variations(
    config: KrnlConfig,
    kernel_info: KernelInfo,
    parents: list[ParentCandidate],
    relevant_principles: list[Principle],
    tracker: OptimizationTracker,
) -> list[GeneratedVariation]:
    """Generate one variation per parent candidate using Claude.

    Each parent in the list produces one Claude call using that parent's
    specific source and NCU metrics as context — so each variation in a
    batch explores a genuinely different branch.
    """
    client = anthropic.Anthropic()

    principles_text = "\n\n".join(p.to_prompt_str() for p in relevant_principles)
    if not principles_text:
        principles_text = "No principles provided."

    dead_ends = tracker.dead_ends_for_llm()
    headroom = tracker.headroom_for_llm()
    history = tracker.history_for_llm()

    variations = []
    for i, parent in enumerate(parents):
        ncu_summary = (
            "\n\n".join(m.summary() for m in parent.ncu_metrics)
            if parent.ncu_metrics
            else "No NCU data."
        )
        bottleneck_summary = (
            "\n\n".join(m.bottleneck_summary() for m in parent.ncu_metrics)
            if parent.ncu_metrics
            else "No bottleneck data."
        )

        prompt = VARIATION_USER_PROMPT.format(
            parent_id=parent.variation_id,
            parent_bottleneck=parent.bottleneck,
            kernel_source=parent.kernel_source,
            launcher_source=parent.launcher_source,
            full_source=parent.full_source,
            ncu_summary=ncu_summary,
            bottleneck_summary=bottleneck_summary,
            headroom=headroom,
            principles_text=principles_text,
            dead_ends=dead_ends,
            history=history,
        )

        # When multiple variations are generated, steer each toward a distinct strategy
        if len(parents) > 1:
            prompt += (
                f"\n\nThis is variation {i + 1} of {len(parents)} being generated this round. "
                "Apply a DIFFERENT optimization strategy than the other variations in this batch."
            )

        response = client.messages.create(
            model=config.model,
            max_tokens=8192,
            system=_build_system_prompt(),
            messages=[{"role": "user", "content": prompt}],
        )

        raw_text = response.content[0].text
        variation = _parse_variation_response(raw_text, parent_id=parent.variation_id)
        if variation:
            variations.append(variation)

    return variations


def _parse_variation_response(response_text: str, parent_id: int) -> GeneratedVariation | None:
    kernel_match = re.search(VARIATION_PARSE_REGEX_KERNEL, response_text, re.DOTALL)
    if not kernel_match:
        return None

    kernel_code = kernel_match.group(1).strip()

    launcher_code = None
    launcher_match = re.search(VARIATION_PARSE_REGEX_LAUNCHER, response_text, re.DOTALL)
    if launcher_match:
        launcher_text = launcher_match.group(1).strip()
        if launcher_text.upper() != "NO CHANGE":
            launcher_code = launcher_text

    principles_section = re.search(
        r"\*\*Principles Applied\*\*:?\s*(.*?)(?=\*\*Predicted Effect\*\*|\*\*Changes Made\*\*)",
        response_text,
        re.DOTALL,
    )
    principles_cited = []
    if principles_section:
        for line in principles_section.group(1).strip().split("\n"):
            line = line.strip().lstrip("- •*")
            if line:
                principles_cited.append(line[:100])

    predicted_effect = ""
    predicted_section = re.search(
        r"\*\*Predicted Effect\*\*:?\s*(.*?)(?=\*\*Changes Made\*\*|\*\*Complete)",
        response_text,
        re.DOTALL,
    )
    if predicted_section:
        predicted_effect = predicted_section.group(1).strip()[:300]

    return GeneratedVariation(
        kernel_code=kernel_code,
        launcher_code=launcher_code,
        principles_cited=principles_cited,
        predicted_effect=predicted_effect,
        raw_response=response_text,
        parent_id=parent_id,
    )
